[theme]
base = "dark"
backgroundColor = "#4da8da"         # lighter marine blue
secondaryBackgroundColor = "#0077b6" # slightly deeper blue for contrast (sidebar etc)
textColor = "#ffffff"                # keep text white for readability
