[theme]
base = "light"
backgroundColor = "#f5f5dc"         # beige
secondaryBackgroundColor = "#e0d8b0" # a slightly darker beige for sidebar and widgets
textColor = "#333333"                # dark gray text for good readability
